#!/bin/bash

find . -type f -name '*.aux' -delete
find . -type f -name '*.bbl' -delete
find . -type f -name '*.blg' -delete
find . -type f -name '*.lof' -delete
find . -type f -name '*.lot' -delete
find . -type f -name '*.toc' -delete
