#!/bin/bash

#
# Docker Imageを用いて，引数のTeXファイルをコンパイルする
#

if [ -z "$3" ]
then 
    docker run --rm -v $PWD:/workdir -u $(id -u):$(id -g) japlateximage \
        sh -c "ptex2pdf -l $2 && ptex2pdf -l $2 && ptex2pdf -l $2"
else
    docker run --rm -v $PWD:/workdir -u $(id -u):$(id -g) japlateximage \
        sh -c "ptex2pdf -l $2 && pbibtex $3 && ptex2pdf -l $2 && ptex2pdf -l $2"
fi	
