#!/bin/bash

#
# Docker Imageを用いて，引数のTeXファイルをコンパイルする
#

if [ -z $IMAGENAME ]
then
    IMAGENAME="japlateximage"
fi

if [ -z "$3" ]
then 
    docker run --rm -v $PWD:/workdir -u $(id -u):$(id -g) $IMAGENAME \
        sh -c "ptex2pdf -l paper.tex && ptex2pdf -l paper.tex && ptex2pdf -l paper.tex"
else
    docker run --rm -v $PWD:/workdir -u $(id -u):$(id -g) $IMAGENAME \
        sh -c "ptex2pdf -l $2 && pbibtex $3 && ptex2pdf -l $2 && ptex2pdf -l $2"
fi	
